module.exports = {
  "4-10": { "saying": "Respect yourself enough to walk away from anything that no longer serves you, grows you, or makes you happy. ", "author": "Robert Tew" },
  "4-11": { "saying": "Start with a simple exercise: always remember, whenever there is a choice, choose the unknown, the risky, the dangerous, the insecure, and you will not be at a loss.", "author": "Osho Rajneesh" },
  "4-12": { "saying": "There is only love, love, nothing but love.", "author": "Swami Muktananda" },
  "4-13": { "saying": "We are not where we live but where we love!", "author": "Dada J.P. Vaswani" },
  "4-14": { "saying": "When one door closes another door opens; but we so often look so long and so regretfully upon the closed door, that we do not see the ones which open for us.", "author": "Alexander Graham Bell" },
  "4-15": { "saying": "Happiness is an attitude of mind, born of the simple determination to be happy under all outward circumstances.", "author": " J. Donald Walters" },
  "4-16": { "saying": "You can spend the whole life worrying, grumbling, brooding over things and being miserable, or the same energy could be used to uplift you to unimaginable heights.", "author": "Sri Sri Ravi Shankar" },
  "4-17": { "saying": "When you spend your hours in thoughts about God, you are also free from evil ways. You will not be tempted to abuse others or harm them in any way. You live in Love, accepting all the events of life as His Gifts.", "author": "Sathya Sai Baba" },
  "4-18": { "saying": "The greatest power is in surrender---surrender to the Divine.", "author": "Sri Sri Ravi Shankar" },
  "4-19": { "saying": "If you want to make an easy job seem mighty hard, just keep putting off doing it.", "author": "Olin Miller" },
  "4-20": { "saying": "Do not confine your studies to this circle and these books. The Universe is the University for you. You can imbibe wisdom from the sky, the clouds, the mountains, the rivers, the daily phenomena of sunrise and sunset, the season, the birds, trees, flowers, insects - in fact all beings and things in the universe.. Approach these teachers with awe, reverence and humility, they will respond with lessons.", "author": "Sathya Sai Baba" },
  "4-21": { "saying": "What makes you weak? Your desire---silly little desire.", "author": "Sri Sri Ravi Shankar" },
  "4-22": { "saying": "The grace of God can be won not by the fasting of the tongue, but by the fasting of the mind.", "author": "Sri Sathya Sai Baba" },
  "4-23": { "saying": "Nivritti Gillette also spoke, saying that we sometimes forget that we are breathing the gift of the same air that the Guru has breathed. We forget that we repeat the mantra whose vibrations the Guru has given us. Then he illustrated his talk, telling of a time when Gurumayi was walking in the gardens carrying a baby. She had to walk very carefully because of the child she was holding. In the same way, he said, we carry something as precious inside us. We carry the Guru, we carry God's love, so we must be very careful how we walk and how we live in order to protect the truth within. ", "author": "Posted on the SYDA Website." },
  "4-24": { "saying": "Be fearless. Lead your life without fear disturbing it. Do not be guided by the opinions and advice of others around you into actions not in line with your conscience.", "author": "Sathya Sai Baba" },
  "4-25": { "saying": "It is only in the depth of that silence that the voice of God can be heard. Speak as low as possible; as little as possible, as sweet as possible.", "author": "Sathya Sai Baba" },
  "4-26": { "saying": "Bondage is not anywhere outside. It is in the mind, in the consciousness.", "author": "Sri Sri Ravi Shankar" },
  "4-27": { "saying": "Whatever is done with anger or excitement makes a strong impression in the mind and that becomes a bondage.", "author": "Sri Sri Ravi Shankar" },
  "4-28": { "saying": "Unless you make some disciplined effort, some Spiritual striving, Grace cannot descend on you.", "author": "Sathya Sai Baba" },
  "4-29": { "saying": "Offering all the negativity, you become free. Offering all the positive virtues you think you possess, you become free.", "author": "Sri Sri Ravi Shankar" },
  "4-30": { "saying": "The Divine is beauty, and beauty is the Divine.", "author": "Sri Sri Ravi Shankar" },
  "4-31": { "saying": "Pay heed to my advice.  Talk as little as possible.", "author": "Sathya Sai Baba" },
  "5-1": { "saying": "Talk only if it is going to enhance the Silence!", "author": "Anon" },
  "5-2": { "saying": "From stillness, everything springs forth.", "author": "Gurumayi Chidvilasananda" },
  "5-3": { "saying": "... keep silent as much as possible ...", "author": "Swami Muktananda" },
  "5-4": { "saying": "When you listen, listen to something more, not just to the sound but to the silence.", "author": "Sri Sri Ravi Shankar" },
  "5-5": { "saying": "Resonate with Stillness", "author": "SYDA" },
  "5-6": { "saying": "True experience of beauty can dawn in silence.", "author": "Sri Sri Ravi Shankar" },
  "5-7": { "saying": "The Self is the formless substratum of everything, the foundation of our lives.  We cannot see it through the eyes, nor can we attain it through speech.  The tongue can speak about it, but the true description of its nature is silence.", "author": "Swami Muktananda" },
  "5-8": { "saying": "Life is a package of surprise gifts for you.", "author": "Sri Sri Ravi Shankar" },
  "5-9": { "saying": "Knowledge of death will improve the quality of your life.", "author": "Sri Sri Ravi Shankar" },
  "5-10": { "saying": "Give up fear and live in bliss.", "author": "Sathya Sai Baba" },
  "5-11": { "saying": "Only you, nothing else.", "author": "Sri Sri Ravi Shankar" },
  "5-12": { "saying": "When you give space, the longing in you increases, whether it is for your spouse, or for God, or for Guru... whatever. And when there is longing, your love becomes really strong, powerful, unshakable.", "author": "Sri Sri Ravi Shankar" },
  "5-13": { "saying": "Suffering is a product of limited knowledge.", "author": "Sri Sri Ravi Shankar" },
  "5-14": { "saying": "The magnitude of the heart is measured by what can disturb you. If it is small like a pond, even a small stone can create big turbulence. If it's like a lake, it needs a bigger stone to create a turbulence. If it's vast, wide like an ocean, nothing can disturb that. Even mountains can fall into the ocean but the ocean remains as it is.", "author": "Sri Sri Ravi Shankar" },
  "5-15": { "saying": "Basing your life on words is very superficial.", "author": "Sri Sri Ravi Shankar" },
  "5-16": { "saying": "The sign of enlightenment is no complaints and no explanations!", "author": "Sri Sri Ravi Shankar" },
  "5-17": { "saying": "Worry is enemy of love.  You cannot be in love and be worried at the same time.", "author": "Sri Sri Ravi Shankar" },
  "5-18": { "saying": "Words cannot capture existence, but silence can.", "author": "Sri Sri Ravishankar" },
  "5-19": { "saying": "Dynamic enthusiasm and infinite patience is the shortest way.", "author": "Sri Sri Ravishankar" },
  "5-20": { "saying": "Learn to sit in a natural manner, Learn to be steady, clam, detached, As you learn to sit still, as you cease to react, your mind will also become steady.", "author": "Swami Muktananada" },
  "5-21": { "saying": "A pure, one-pointed mind, a simple and comfortable posture, repetition of the Guru's name - these are the marks of a seeker.", "author": "Swami Muktananda" },
  "5-22": { "saying": "The music of the heart sweetens your being and strengthens it at the same time.  Spellbound by the whisper of a memory that you have heard this music before, you set out in search of the cave of the heart where the unstruck sound resonates.  Seekers of all generations have walked the path before you.  Those who hear the sound once again and lead their lives in harmony with it are called saints and great beings.", "author": "Swami Chidvilasananda" },
  "5-23": { "saying": "Love is not happening; love is being.  Love is not an act; it is existence. Love is not emotion; it's your very nature.", "author": "Sri Sri Ravi Shankar" },
  "5-24": { "saying": "Love is love.  Respect is love.  The heart is also love - and so are you.", "author": "Swami Chidvilasananda" },
  "5-25": { "saying": "There is only love, love, nothing but love.", "author": "Swami Muktananda" },
  "5-26": { "saying": "Love is the magnificence of the souls existence.", "author": "Swami Muktananda" },
  "5-27": { "saying": "What we are is the love that is present when all else has come and gone.", "author": "Brandon Bays" },
  "5-28": { "saying": "Relationship is what? Feeling no separation-I am you, you are me. You are part of me, I am part of you.", "author": "Sri Sri Ravi Shankar" },
  "5-29": { "saying": "Be calm and without agitation under all conditions.", "author": "Sri Sathya Sai Baba" },
  "5-30": { "saying": "In outward forms and in the depth of things, behold yourself. You are the Truth.", "author": "Sathya Sai Baba" },
  "6-1": { "saying": "Silence is not a matter of resolve! It is always there. Silence is the endless flow of Pure God into you, into the world.", "author": "Sathya Sai Baba" },
  "6-2": { "saying": "Grace is showered on those who seek. Knock, and the door shall be opened, Ask, and food will be served; Search, and the treasure will be yours.", "author": "Sathya Sai Baba" },
  "6-3": { "saying": "Practice random acts of kindness and Senseless acts of beauty.", "author": "Anon" },
  "6-4": { "saying": "Do not come to Me with your hands full of trash, for how can I fill them with Grace when they are already full?  Come with empty hands and carry away My treasure, My Love.", "author": "Sathya Sai Baba" },
  "6-5": { "saying": "It is better to keep your mouth shut and to appear stupid than to open it and remove all doubt.", "author": "Mark Twain" },
  "6-6": { "saying": "He who joyfully marches to music in rank and file has already earned my contempt. He has been given a large brain by mistake, since for him the spinal cord would suffice.", "author": "Albert Einstein" },
  "6-7": { "saying": "I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", "author": "Albert Einstein" },
  "6-8": { "saying": "Intense love does not measure, it just gives.", "author": "Mother Teresa" },
  "6-9": { "saying": "I don't want to live. I want to love first, and live incidentally.", "author": " Zelda Fitzgerald" },
  "6-10": { "saying": "Love is but the discovery of ourselves in others, and the delight in the recognition.", "author": "Alexander Smith" },
  "6-11": { "saying": "We come to love not by finding a perfect person but by learning to see an imperfect person perfectly.", "author": "Sam Keen" },
  "6-12": { "saying": "Embodiments of love!   Regard love as your life breath  and as the sole purpose of your existence.", "author": "Sathya Sai Baba" },
  "6-13": { "saying": "Whatever you do, allow it to come from that great love.  Whatever you think, let there be love.", "author": "Gurumayi Chidvilasananda" },
  "6-14": { "saying": "Are you building a bridge to the inner country?", "author": "Gurumayi Chidvilasananda" },
  "6-15": { "saying": "The moment you decide to open your heart to grace you will be filled.", "author": "Swami Muktananda" },
  "6-16": { "saying": "Show only scenes of love to the witness behind the eyes.", "author": "Swami Muktananda" },
  "6-17": { "saying": "I want you to be courageous and strong. I want you to be able to look into the eyes of your brothers and sisters, and give and receive love. Continually access your own deeper power, your greater power so that you can literally send your blessings to everyone, everywhere who needs to experience them. ", "author": "Gurumayi Chidvilasananda" },
  "6-18": { "saying": "Brahma said to Vasistha: ... Whatever appears in one's consciousness, that seems to come into being, gets established, and bears fruits!  Such is the power of the mind.  ... It is the mind that makes things appear here.  It brings about the appearance of the body, etc.  Naught else is aware of the body.", "author": "Vasisthas Yoga" },
  "6-19": { "saying": "Vasistha telling Ram: Even when the light of wisdom shines on the life of the deluded mind, it foolishly rejects it, considering that that wisdom is its enemy.  Then it weeps and wails in distress.  Sometimes, it experiences an imperfect awakening, and renounces the pleasures of the world without proper understanding - such renunciation itself proves to be a great source  of sorrow.  But, when such renunciation arises out of the fullness of understanding, of wisdom born of enquiry into the nature of the mind, the renunciation leads to supreme bliss.", "author": "Vasisthas Yoga" },
  "6-20": { "saying": "Vasistha telling Ram: The mind itself appears as wind in the moving element, luster in the lustrous, solidity in earth and void in space.  If 'the mind is elsewhere' the taste of food that is being eaten is not really experienced.  If 'the mind is elsewhere' one does not see what is right in front of oneself.  The senses are born of the mind, but not the other way round.", "author": "Vasisthas Yoga" },
  "6-21": { "saying": "… journal writing as a spiritual practice involves learning to articulate with precision and clarity what is happening in our sadhana.  When we review and contemplate our experiences verbally through writing, we are also anchoring in our awareness the lessons we learn.  Then we can draw upon them again and express the teaching they illustrate, not only to others, but also to ourselves.  The attempt to articulate our learning through writing, through meaningful images, and in conversations with fellow sadhakas, draws the teachings into our life.", "author": "Swami Anantananda" },
  "6-22": { "saying": "To accept the challenge of the unknown, in spite of all fears, is courage.", "author": "Osho Rajneesh" },
  "6-23": { "saying": "In a story describing a sanyasin: He is so powerful that in his presence you simply forget the whole world.  He is magnetic, and a great silence surrounds him and the whole area feels as if it is delighting in the man.", "author": "Osho Rajneesh" },
  "6-24": { "saying": "The way of the heart is the way of courage.  It is to live in insecurity; it is to live in love, and trust; it is to move in the unknown.  It is leaving the past and allowing the future to be.", "author": "Osho Rajneesh" },
  "6-25": { "saying": "My responsibility is toward my heart, not toward anybody else in the world.  So is your responsibility only toward your own being.  Don't go against it, because going against it is committing suicide, is destroying yourself.  [Following your heart will]... nourish your being.", "author": "Osho Rajneesh" },
  "6-26": { "saying": "Commit as many mistakes as possible, remembering only one thing: don't commit the same mistake again.  And you will be growing.", "author": "Osho Rajneesh" },
  "6-27": { "saying": "... don't miss any opportunity; whatsoever opportunity comes, go into it.  Always choose life and always choose doing; never withdraw, never escape.  Enjoy any opportunity that comes on your way to do something, to be creative.", "author": "Osho Rajneesh" },
  "6-28": { "saying": "This is the key: if you become aware of anything in your memory, you are freed from it.  Awareness liberates, unconsciousness creates a bondage.", "author": "Osho Rajneesh" },
  "6-29": { "saying": "The moment you accept yourself without any conditions, suddenly an outburst of joy happens.  Your juices start flowing, your life really becomes ecstatic.", "author": "Osho Rajneesh" },
  "6-30": { "saying": "individuality is raw, wild, strong, with tremendous power.", "author": "Osho Rajneesh" },
  "6-31": { "saying": "If you bring it to consciousness it starts evaporating.", "author": "Osho Rajneesh" },
  "7-1": { "saying": "Only a silence that can face problems and remain silent is something to be longed for, to be desired.", "author": "Osho Rajneesh" },
  "7-2": { "saying": "Man is freedom.", "author": "Osho Rajneesh" },
  "7-3": { "saying": "Never miss the unknown.  Always choose the unknown and go headlong.  Even if you suffer, it is worth it- it always pays.  You always come out of it more grown up, more mature, more intelligent.", "author": "Osho Rajneesh" },
  "7-4": { "saying": "You can go beyond... It is within your power and it is your right.  But you will have to make the small effort to move from mind to no-mind.", "author": "Osho Rajneesh" },
  "7-5": { "saying": "Risk is the only guarantee for being truly alive.", "author": "Osho Rajneesh" },
  "7-6": { "saying": "Meditation is nothing but the discovery of the inner sense.", "author": "Osho Rajneesh" },
  "7-7": { "saying": "Only those that are ready to become nothing, utterly empty of themselves, are able to receive the gift of love from the beyond.", "author": "Osho Rajneesh" },
  "7-8": { "saying": "In love the ego has to disappear.  In love you are no longer separate - love helps you to dissolve with others.  It is a meeting and a merger.", "author": "Osho Rajneesh" },
  "7-9": { "saying": "Meditation is nothing but creating a situation where the mind has less and less things to do.", "author": "Osho Rajneesh" },
  "7-10": { "saying": "Deep sexual orgasm gives the body at-homeness.  A very, very deep health happens in the body because the body feels whole.", "author": "Osho Rajneesh" },
  "7-11": { "saying": "Fear is nothing but absence of love.  Do something with love, forget about fear.  If you love well, fear disappears.", "author": "Osho Rajneesh" },
  "7-12": { "saying": "Whatever happens, remind youself of this: the Heart, the divine splendor, is your home and final destination.", "author": "Gurumayi Chidvilasananda" },
  "7-13": { "saying": "Deprive your small self of the trivial, fleeting satisfactions of maya, the world of illusion, and allow the experience of pure love to stream forth.", "author": "Gurumayi Chidvilasananda" },
  "7-14": { "saying": "Let yourself be captivated by the luminocity of the inner world.", "author": "Gurumayi Chidvilasananda" },
  "7-15": { "saying": "Each individual is governed by his or her own destiny... To enter the Heart and perceive divinity, you must obey the rules of your spiritual path.", "author": "Gurumayi Chidvilasananda" },
  "7-16": { "saying": "[The] abundant grace of the Master... [freely] and spontaneously... enters the lives of seekers.  Yet for the Guru's grace to unfold in its fullness, it demands that seekers put forth a sincere effort to reach the goal of their seeking.", "author": "Gurumayi Chidvilasananda" },
  "7-17": { "saying": "To be filled with enthusiasm means to give yourself completely to God and let God steer the wheel of your life.", "author": "Gurumayi Chidvilasananda" },
  "7-18": { "saying": "Each aesthetic experience should be enjoyed mindfully and with a disciplined intention.  This intention is directed toward heightening the general level of our sensitivity to beauty.  In that way, every bit of beauty that you encounter will bring you closer to a sustained sense of wonder.", "author": "Gurumayi Chidvilasananda" },
  "7-19": { "saying": "Do not judge whether what you are doing is impressive or mediocre, spiritual or mundane.  Just do it with enthusiasm.", "author": "Gurumayi Chidvilasananda" },
  "7-20": { "saying": "Walk happily.  Speak sweetly.", "author": "Gurumayi Chidvilasananda" },
  "7-21": { "saying": "Summon forth the power of your inner courage and live the life of your dreams.", "author": "Gurumayi Chidvilasananda" },
  "7-22": { "saying": "Have the courage to find the best outcome in every situation.", "author": "Gurumayi Chidvilasananda" },
  "7-23": { "saying": "Courage destroys ego.", "author": "Swami Muktananda" },
  "7-24": { "saying": "Listen to the messages that life provides.", "author": "Gurumayi Chidvilasananda" },
  "7-25": { "saying": "It requires steady, quiet effort to keep the heart producing the rasa, the sweet flavour, of contentment.", "author": "Gurumayi Chidvilasananda" },
  "7-26": { "saying": "Whenever you think you are helpless, you are denying God's grace and the Guru's blessings.", "author": "Gurumayi Chidvilasananda" },
  "7-27": { "saying": "Learn to remember God.  Learn to rethink each thought.  Learn to reshape each action.  Learn to reexamine your own heart.  Learn to renew your understanding of what you have heard.", "author": "Gurumayi Chidvilasananda" },
  "7-28": { "saying": "A genuine smile truly opens the heart.", "author": "Gurumayi Chidvilasananda" },
  "7-29": { "saying": "Make yourself a great giver of good fortune.  Make yourself a refreshing lake.  Make yourself an abode of fulfilling resolutions.", "author": "Gurumayi Chidvilasananda" },
  "7-30": { "saying": "So by smiling at your destiny, you bring out the best in it.", "author": "Gurumayi Chidvilasananda" },
  "7-31": { "saying": "Be happy.  Have great joy and bliss, and always smile.", "author": "Swami Muktananda quoted by Gurumayi Chidvilasananda" },
  "8-1": { "saying": "With a fresh young spirit, walk the path.", "author": "Gurumayi Chidvilasananda" },
  "8-2": { "saying": "The more profound our reverence and regard for the Guru, the deeper and firmir our spiritual progress becomes.", "author": "Swami Muktananda" },
  "8-3": { "saying": "In fact, a true disciple is one who merges his entire individuality into that of his Guru.  As a matter of fact, a true devotee is one who has merged his identity with God; a perfect yogi is one who is always in communion with his inner Self; and likewise, a true disciple is one whose atman is forever united with that of the Guru.", "author": "Swami Muktananda" },
  "8-4": { "saying": "Believe it or not, laziness is caused mainly by a lack of discipline in eating.  When eating is undisciplined, all the internal organs become sluggish from overwork.  The consequences of this are listlessness and apathy.  Laziness of the body, laziness of the mind, laziness of the heart - these things can often be traced to foolish destructive eating.", "author": " Gurumayi Chidvilasanandain" },
  "8-5": { "saying": "If you hear ethereal sounds within, respect them and let your mind become absorbed in them.", "author": "Gurumayi Chidvilasanandain" },
  "8-6": { "saying": "Whatever worldly noise you hear, listen for the ethereal sound in that noise.", "author": "Gurumayi Chidvilasanandain" },
  "8-7": { "saying": "The Mantra does not bear fruit where there is excessive eating.", "author": "Kularnava Tantra (15.107) quoted by Gurumayi Chidvilasananda" },
  "8-8": { "saying": "Don't fast.  Just eat in moderation.  Eat in a disciplined way, and when you're not hungry, don't eat.  That is the best fast.", "author": "Muktananda quoted by Gurumayi Chidvilasanandain" },
  "8-9": { "saying": "You should never judge what another person eats.", "author": "Gurumayi Chidvilasanandain" },
  "8-10": { "saying": "For your spiritual practices to bear fruit, discipline in eating is crucial.", "author": "Gurumayi Chidvilasanandain" },
  "8-11": { "saying": "Even when sensation of pleasure arises on contact with the objects let it lead you inward to the self.", "author": "Vasistha in Yoga Vasishta" },
  "8-12": { "saying": "If  this delusion is not repeatedly revived, it ceases to be.", "author": "Vasistha in Yoga Vasishta" },
  "8-13": { "saying": "Hence, let your consciousness or your awakened intelligence realise that the egosense ('I') is not, and then be what you are.", "author": "Bhusunda in Yoga Vasishta" },
  "8-14": { "saying": "The light of consciousness is the Self.", "author": "Bhusunda in Yoga Vasishta" },
  "8-15": { "saying": "With rapt attention you have been listening to this talk ... Let there be the same concentration and deep awareness as you go about the other activities of your life today, tomorrow, and the rest of your life.", "author": "Gurumayi Chidvilasanandain" },
  "8-16": { "saying": "When it comes to the experience of  the highest Truth, serenity of mind is essential. And that serenity is the fruit of consistent discipline. It cannot be sustained any other way.", "author": "Gurumayi Chidvilasanandain" },
  "8-17": { "saying": "This awareness [of Spanda] can be achieved by attending to the first movement of the will, discovered when we are fully present to ourselves in the actuality of our situation.  Every instant is a new beginning which abides in the eternity of the self-perpetuating present where all ‘beginnings’ cease.  The closer we come to experiencing the moment in which the impulse to action arises, the more directly we come in contact with the concrete actuality of the present and the authenticity of our Being.  Thus the Spanda teachings instruct the yogi to maintain an alert awareness of the continuity of his consciousness throughout his every action.", "author": "Mark S. G. Dyczkowski" },
  "8-18": { "saying": "May Shiva Who has penetrated and become one with me, worship Himself thus by means of His own power that He may Himself reveal His own nature.", "author": "Shivadrishti as quoted by Mark S. G. Dyczkowski" },
  "8-19": { "saying": "Amateurs practice until they can get it right; professionals practice until they can't get it wrong.", "author": "Anon" },
  "8-20": { "saying": "Empty your cup, start from the beginning.", "author": "Old Chinese Saying" },
  "8-21": { "saying": "When the mind returns to its natural abode, there is neither a path nor anyone to traverse it.", "author": " Gurumayi Chidvilasananda" },
  "8-22": { "saying": "How many people are happier because you were born?", "author": "Joan Grant" },
  "8-23": { "saying": "The entire world is the play of the universal Consciousness.  One who sees it in this way becomes liberated while in the body.", "author": "Spanda Karikas" },
  "8-24": { "saying": "Inside us lies every possibility that is available to a sentient being.  Every darkness, every light.  It is the choices we make that decide who or what we will be.", "author": "Charles de Lint" },
  "8-25": { "saying": "Master, of thy wisdom let me grow into a great tree, so that the sorrowful may rest in my shade and go on their journey refreshed, and the weary regain their strength in the shelter of my branches.", "author": "Joan Grant" },
  "8-26": { "saying": "Just by remembering the Guru, you attain everything that you must attain - you attain liberation.", "author": "Gurumayi Chidvilasananda" },
  "8-27": { "saying": "Complete your sadhana with a brave heart.", "author": "Gurumyi Chidvilasananda" },
  "8-28": { "saying": "Because I have lived there is less fear among men; because I kept faith the lamp I lit can never be put out.", "author": "Joan Grant" },
  "8-29": { "saying": "Strive not to be a success but rather to be of value.", "author": "Albert Einstein" },
  "8-30": { "saying": "Sometimes I wonder whether the world is being run by smart people who are putting us on or by imbeciles who really mean it.", "author": " Mark Twain" },
  "9-1": { "saying": "People say walking on water is a miracle, but to me walking peacefully on earth is the real miracle.", "author": "Thich Nhat Hanh" },
  "9-2": { "saying": "What you do today can improve all your tomorrows.", "author": "Ralph Marston" },
  "9-3": { "saying": "In order to succeed, we must first believe that we can.", "author": "Nikos Kazantzakis" },
  "9-4": { "saying": "If you can dream it, you can do it.", "author": "Walt Disney" },
  "9-5": { "saying": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe" },
  "9-6": { "saying": "Acknowledging the good that you already have in your life is the foundation for all abundance.", "author": "Eckhart Tolle" },
  "9-7": { "saying": "Nothing is permanent in this wicked world, not even your troubles. ", "author": "Charlie Chaplin" },
  "9-8": { "saying": "Absorb what is useful. Discard what is not. Add what is uniquely your own. ", "author": "Bruce Lee" },
  "9-9": { "saying": "Let us always meet each other with a smile, for smile is the beginning of love.", "author": "Mother Teresa" },
  "9-10": { "saying": "What makes you weak? Your desire ... silly little desire.", "author": "Sri Sri Ravi Shankar" },
  "9-11": { "saying": "The best preparation for tomorrow is doing your best today. ", "author": "H. Jackson Brown Jr." },
  "9-12": { "saying": "We are born of love.  Love is our mother.", "author": "Rumi" },
  "9-13": { "saying": "Where there is love there is life.", "author": "Mahatma Gandhi" },
  "9-14": { "saying": "Start by doing what's necessary, then do what's possible, and suddenly you are doing the impossible.", "author": "Francis of Assisi" },
  "9-15": { "saying": "Put your heart, mind, and soul into even the smallest acts.  This is the secret of success.", "author": "Swami Sivananda" },
  "9-16": { "saying": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale" },
  "9-17": { "saying": "Do not take life too seriously. You will never get out of it alive.", "author": "Elbert Hubbard" },
  "9-18": { "saying": "I love deadlines.  I like the wooshing sound they make as they fly by.", "author": "Douglas Adams" },
  "9-19": { "saying": "Positive anything is better than negative nothing.", "author": "Elbert Hubbard" },
  "9-20": { "saying": "Those who are not aware they are walking in darkness will never seek the light.", "author": "Bruce Lee"},
  "9-21": {"saying": "The only thing that matters in software development is that your users love the software.", "author": "Eric Elliot"},
  "9-22": {"saying": "If you change nothing, nothing will change", "author": "Tony Robbins"}
};

